# Generated by Django 4.0.5 on 2022-08-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descroption',
            new_name='description',
        ),
    ]
